### ISSUE TITLE
Vehicles collides with waypoint

### ISSUE THREAD

**Issue by LeMuitque** [mchrbn/unity-traffic-simulation#10]
Hello!

Thank you for sharing such a great sytem. I've been trying to implement it on my project and I have only one issue. When a vehicle approach a waypoint it create a collision, yet every parameters with your demo version are the same. I've tried nearly everything but it's still doesn't seems to work. Layers and tags are set, colliders are also set on vehicles and waypoints,

I'm using last version of your code and last version of Unity, thx for your help!

**Comment by MSchmoecker** [comment]
This is because of the collider for the waypoint is set at the "UnityEditor" (10th) layer. You need to exclude them from the Layer Collision Matrix in the Project Settings under Physics. I’m sorry for not editing the documentation.

Set it like this:
![grafik](https://user-images.githubusercontent.com/39767545/75905935-1322f080-5e46-11ea-9f9e-150c40eedbf6.png)



I find the solution with not very clean, I will probably try to make it work without colliders and instead calculate the intersection with the ray. 

I hope I could help you

**Comment by LeMuitque** [comment]
Thank you so much that solved the issue and everything works perfectly now. Really appreciated!

**Comment by LeMuitque** [comment]
Hey! Sorry to re-open this issue. Well I'm having some difficulties with speed settings, tried to play with all parameters but I can't really understand which one is for. My issue is that acceleration is way too low. Base speed is like perfect but once my car turn or stop it takes a lot of time to get back to a normal speed.. Some hints on how to play with parameters could be very useful. Thx!

**Comment by mchrbn** [comment]
New update should be more comprehensive for speed (add more torque)
