### ISSUE TITLE
New Cars collides with others

### ISSUE THREAD

**Issue by menez1111** [mchrbn/unity-traffic-simulation#16]
I added new cars and I used Vehicle Phycischs script but other cars hits the new car and new car hits old ( from prefab) cars. Also my new car always wait on Intersection even if there is no car.
![image](https://user-images.githubusercontent.com/53665690/92753833-ee7a7900-f392-11ea-8046-a6c63c97f0cf.png)

**Comment by mchrbn** [comment]
Can you share your project or just export your car as a prefab, so I can check, like that it's difficult to tell.

**Comment by menez1111** [comment]
Could I send it by e-mail ? Also, now I have a bigger problem.

**Comment by mchrbn** [comment]
Upload it on Github if possible

**Comment by mchrbn** [comment]
I checked your project, for that issue, the problem is that you put the Raycast Anchor too low so it is not hitting the other cars collider:

![01](https://user-images.githubusercontent.com/660455/93535738-32b0df00-f97a-11ea-8b13-347c28758f58.JPG)

You have to set it up higher like so:

![02](https://user-images.githubusercontent.com/660455/93535973-a226ce80-f97a-11ea-8dab-d0b36e471fba.JPG)

**Comment by menez1111** [comment]
I will fix it thanks

**Comment by menez1111** [comment]
It worked
